[book]
authors = ["Mohammad Ahmad ALhamad"]
language = "en"
multilingual = false
src = "src"
title = "Digital Craft Design"

[output.html]
# theme = "light"
default-theme = "light"
preferred-dark-theme = "light"